from flask import Flask, render_template, request
from predict import predict_variant_class
from generate_html_graph import generate_bar_graph_html
from flask import jsonify
from flask import send_file
from flask import session
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import ListFlowable, ListItem
from reportlab.lib.units import inch
from reportlab.platypus import Image
from generate_html_graph import generate_bar_graph_image
import io


app = Flask(__name__)

app.secret_key = "e6dfb912-0db6-4c08-af09-da48993a4b97"

@app.route('/', methods=["GET", "POST"])
def home():
    if request.method == "POST":
        medical_text = request.form.get("medical_text")
        predicted_class, confidence, class_results, feature_results = predict_variant_class(medical_text)

        # Store results in session
        session["medical_text"] = medical_text
        session["predicted_class"] = int(predicted_class)
        session["confidence"] = float(confidence)
        session["class_results"] = class_results
        session["feature_results"] = feature_results
        
        class_graph = generate_bar_graph_html(class_results, graph_type="class")
        feature_graph = generate_bar_graph_html(feature_results, graph_type="features")
        
        return render_template(
            'main.html', 
            medical_text=medical_text,
            predicted_class=predicted_class, 
            confidence=f"{confidence:.2f}", 
            class_graph=class_graph,
            feature_graph=feature_graph,
        )

    return render_template('main.html')

@app.route("/export/json")
def export_json():

    if "predicted_class" not in session:
        return jsonify({"error": "No prediction available"}), 400

    results_payload = {
        "medical_text": session.get("medical_text"),
        "predicted_class": session.get("predicted_class"),
        "confidence": session.get("confidence"),
        "class_probabilities": session.get("class_results"),
        "top_medical_features": session.get("feature_results")
    }

    return jsonify(results_payload)

@app.route("/export/pdf")
def export_pdf():

    if "feature_results" not in session:
        return "No prediction available. Please classify first.", 400

    medical_text = session.get("medical_text")
    predicted_class = session.get("predicted_class")
    confidence = session.get("confidence")
    feature_results = session.get("feature_results")
    class_results = session.get("class_results")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    elements.append(Paragraph("Clinical Variant Interpretation Report", styles["Heading1"]))
    elements.append(Spacer(1, 0.3 * inch))

    elements.append(Paragraph(f"<b>Medical Text:</b> {medical_text}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Predicted Class:</b> {predicted_class}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Confidence:</b> {confidence:.2f}%", styles["Normal"]))
    elements.append(Spacer(1, 0.3 * inch))

    # --- CLASS GRAPH ---
    class_img_buffer = generate_bar_graph_image(class_results, "class")
    if class_img_buffer:
        elements.append(Paragraph("<b>Class Probability Distribution</b>", styles["Heading3"]))
        elements.append(Spacer(1, 0.2 * inch))
        elements.append(Image(class_img_buffer, width=450, height=250))
        elements.append(Spacer(1, 0.3 * inch))

    # --- FEATURE GRAPH ---
    feature_img_buffer = generate_bar_graph_image(feature_results, "features")
    if feature_img_buffer:
        elements.append(Paragraph("<b>Top Influential Medical Features</b>", styles["Heading3"]))
        elements.append(Spacer(0.5, 0.2 * inch))
        elements.append(Image(feature_img_buffer, width=450, height=250))
        elements.append(Spacer(1, 0.3 * inch))

    elements.append(Paragraph(
        "Disclaimer: This report is generated by a research-grade AI system "
        "and must not be used for medical decision-making without expert review.",
        styles["Italic"]
    ))

    doc.build(elements)
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="clinical_variant_report.pdf",
        mimetype="application/pdf"
    )

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=7860)
